version: '3.9'
services:
  backend:
    container_name: elk-backend
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ./logs:/app/logs
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://192.168.55.104:8600"
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      - ELASTIC_APM_SERVER_URL=http://192.168.55.104:8200
    networks:
      - elk

networks:
  elk:
    driver: bridge